### ISSUE TITLE
GUI Hanging

### ISSUE THREAD

**Issue by oreodave** [danielandastro/Numbench#3]
**Describe the bug**
The GUI hangs during the calculation and benchmarking of the system. 

**To Reproduce**
Run the program in either release or debug versions and click the "Begin Calculation" button

**Expected behavior**
Upon clicking it, the GUI becomes unresponsive for roughly 10-20 seconds.

**Screenshots**

**Desktop:**
 - OS: Windows 10 OS
 - Local application
 - Latest

**Additional notes**
I would consider optimising the calculations and using [async processes](https://docs.microsoft.com/en-gb/dotnet/csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await) to make the GUI responsive during calculation.

**Comment by danielandastro** [comment]
Thanks for raising this issue @Oreodave, I will definitely look into this, currently I am in the throws of traveling p, as soon as I reach my destination I will begin solving the issue

**Comment by danielandastro** [comment]
@JohnGanga can you attempt to solve this in a new branch

**Comment by oreodave** [comment]
@danielandastro sorry to be a bother, would it be possible for me to also work on this? I'd love to offer my services!

**Comment by danielandastro** [comment]
Sure I’ll give you push access?

**Comment by oreodave** [comment]
@danielandastro nah that's fine, atm ill dev on my branch and send pull requests. That way we have a better method of discussing additions/improvements, I think

**Comment by danielandastro** [comment]
Solved, Putting solution up shortly
